version: '3'

services:
  db:
    image: postgres:14.3
    ports:
      - "${PGPORT}:5432"
    environment:
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: '${PGDB}'
    container_name: tattoo-manager-db
    volumes:
      - ./postgres:/var/lib/postgresql/data